### ISSUE TITLE
add presets of indicators

### ISSUE THREAD

**Issue by andbiz** [MPBA/pyHRV#42]
e.g.:

ph.HRV_TimeDomain()
ph.HRV_FrequencyDomain()

returns a list for fmap

**Comment by Alebat** [comment]
Considering:
- add a module presets (ph.presets.hrv()) or leave them in the __init__
- hybrid property or function?
- singletons?

**Comment by andbiz** [comment]
Create two subsets of hrv indicators: td_hrv and fd_hrv

**Comment by andbiz** [comment]
Solved (550f15c) 

Pls check

**Comment by Alebat** [comment]
If it works it is ok, I will fix spacing and code style
