### ISSUE TITLE
MIssing get_params()

### ISSUE THREAD

**Issue by andbiz** [MPBA/pyHRV#44]
This method has been apparently (wrongly) removed.

**Comment by andbiz** [comment]
Solved (8af18d2) [?]

Pls check.

**Comment by Alebat** [comment]
I renamed it get() according to the set method, to be semantically coherent. I will revert this commit ok?

**Comment by andbiz** [comment]
Isn't get() already used for cache-related functions?

**Comment by Alebat** [comment]
No more, the algorithm is in the method `algorithm` and it can be run cached by the `run` method
